import React, { Component } from 'react';

export default class Home extends React.Component {
	render() {
		return (
			<div className="red bg">
				<h1>
		        	HOME!
		        </h1>
		        <p>lorem30Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id urna ut nisi pharetra cursus. Nulla facilisi. Ut finibus tincidunt tellus eget ultrices. Praesent tempor, sapien vitae tempus dapibus, elit enim volutpat sem, in pellentesque ex eros ac lectus. Suspendisse nec malesuada felis, vitae aliquet felis. Aenean aliquam fermentum erat, sed aliquam velit mollis quis. Vestibulum porta tempor eros. Vestibulum et leo in arcu maximus tincidunt. Sed mollis varius sollicitudin. Nunc commodo ornare nisi, imperdiet sagittis arcu dapibus et. Pellentesque facilisis nisl turpis, ut tincidunt mi ornare at. Donec fermentum gravida eleifend. Donec aliquet lorem vel risus placerat congue. Donec convallis scelerisque ante, ut dictum urna. Integer dui ligula, fermentum id tempus vel, posuere quis leo.</p>
		        <p>lorem30Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id urna ut nisi pharetra cursus. Nulla facilisi. Ut finibus tincidunt tellus eget ultrices. Praesent tempor, sapien vitae tempus dapibus, elit enim volutpat sem, in pellentesque ex eros ac lectus. Suspendisse nec malesuada felis, vitae aliquet felis. Aenean aliquam fermentum erat, sed aliquam velit mollis quis. Vestibulum porta tempor eros. Vestibulum et leo in arcu maximus tincidunt. Sed mollis varius sollicitudin. Nunc commodo ornare nisi, imperdiet sagittis arcu dapibus et. Pellentesque facilisis nisl turpis, ut tincidunt mi ornare at. Donec fermentum gravida eleifend. Donec aliquet lorem vel risus placerat congue. Donec convallis scelerisque ante, ut dictum urna. Integer dui ligula, fermentum id tempus vel, posuere quis leo.</p>
		        <p>lorem30Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id urna ut nisi pharetra cursus. Nulla facilisi. Ut finibus tincidunt tellus eget ultrices. Praesent tempor, sapien vitae tempus dapibus, elit enim volutpat sem, in pellentesque ex eros ac lectus. Suspendisse nec malesuada felis, vitae aliquet felis. Aenean aliquam fermentum erat, sed aliquam velit mollis quis. Vestibulum porta tempor eros. Vestibulum et leo in arcu maximus tincidunt. Sed mollis varius sollicitudin. Nunc commodo ornare nisi, imperdiet sagittis arcu dapibus et. Pellentesque facilisis nisl turpis, ut tincidunt mi ornare at. Donec fermentum gravida eleifend. Donec aliquet lorem vel risus placerat congue. Donec convallis scelerisque ante, ut dictum urna. Integer dui ligula, fermentum id tempus vel, posuere quis leo.</p>
		        <p>lorem30Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id urna ut nisi pharetra cursus. Nulla facilisi. Ut finibus tincidunt tellus eget ultrices. Praesent tempor, sapien vitae tempus dapibus, elit enim volutpat sem, in pellentesque ex eros ac lectus. Suspendisse nec malesuada felis, vitae aliquet felis. Aenean aliquam fermentum erat, sed aliquam velit mollis quis. Vestibulum porta tempor eros. Vestibulum et leo in arcu maximus tincidunt. Sed mollis varius sollicitudin. Nunc commodo ornare nisi, imperdiet sagittis arcu dapibus et. Pellentesque facilisis nisl turpis, ut tincidunt mi ornare at. Donec fermentum gravida eleifend. Donec aliquet lorem vel risus placerat congue. Donec convallis scelerisque ante, ut dictum urna. Integer dui ligula, fermentum id tempus vel, posuere quis leo.</p>
		        <p>lorem30Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id urna ut nisi pharetra cursus. Nulla facilisi. Ut finibus tincidunt tellus eget ultrices. Praesent tempor, sapien vitae tempus dapibus, elit enim volutpat sem, in pellentesque ex eros ac lectus. Suspendisse nec malesuada felis, vitae aliquet felis. Aenean aliquam fermentum erat, sed aliquam velit mollis quis. Vestibulum porta tempor eros. Vestibulum et leo in arcu maximus tincidunt. Sed mollis varius sollicitudin. Nunc commodo ornare nisi, imperdiet sagittis arcu dapibus et. Pellentesque facilisis nisl turpis, ut tincidunt mi ornare at. Donec fermentum gravida eleifend. Donec aliquet lorem vel risus placerat congue. Donec convallis scelerisque ante, ut dictum urna. Integer dui ligula, fermentum id tempus vel, posuere quis leo.</p>
		        <p>lorem30Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id urna ut nisi pharetra cursus. Nulla facilisi. Ut finibus tincidunt tellus eget ultrices. Praesent tempor, sapien vitae tempus dapibus, elit enim volutpat sem, in pellentesque ex eros ac lectus. Suspendisse nec malesuada felis, vitae aliquet felis. Aenean aliquam fermentum erat, sed aliquam velit mollis quis. Vestibulum porta tempor eros. Vestibulum et leo in arcu maximus tincidunt. Sed mollis varius sollicitudin. Nunc commodo ornare nisi, imperdiet sagittis arcu dapibus et. Pellentesque facilisis nisl turpis, ut tincidunt mi ornare at. Donec fermentum gravida eleifend. Donec aliquet lorem vel risus placerat congue. Donec convallis scelerisque ante, ut dictum urna. Integer dui ligula, fermentum id tempus vel, posuere quis leo.</p>
	        </div>
		);
	}
}